<?php

namespace CageA80\FedEx\Support;

class ServiceType
{
    const EUROPE_FIRST_INTERNATIONAL_PRIORITY = 'EUROPE_FIRST_INTERNATIONAL_PRIORITY';
    const FEDEX_1_DAY_FREIGHT = 'FEDEX_1_DAY_FREIGHT';
    const FEDEX_2_DAY = 'FEDEX_2_DAY';
    const FEDEX_2_DAY_AM = 'FEDEX_2_DAY_AM';
    const FEDEX_2_DAY_FREIGHT = 'FEDEX_2_DAY_FREIGHT';
    const FEDEX_3_DAY_FREIGHT = 'FEDEX_3_DAY_FREIGHT';
    const FEDEX_DISTANCE_DEFERRED = 'FEDEX_DISTANCE_DEFERRED';
    const FEDEX_EXPRESS_SAVER = 'FEDEX_EXPRESS_SAVER';
    const FEDEX_GROUND = 'FEDEX_GROUND';
    const FEDEX_INTERNATIONAL_PRIORITY = 'FEDEX_INTERNATIONAL_PRIORITY';
    const FEDEX_NEXT_DAY_AFTERNOON = 'FEDEX_NEXT_DAY_AFTERNOON';
    const FEDEX_NEXT_DAY_EARLY_MORNING = 'FEDEX_NEXT_DAY_EARLY_MORNING';
    const FEDEX_NEXT_DAY_END_OF_DAY = 'FEDEX_NEXT_DAY_END_OF_DAY';
    const FEDEX_NEXT_DAY_FREIGHT = 'FEDEX_NEXT_DAY_FREIGHT';
    const FEDEX_NEXT_DAY_MID_MORNING = 'FEDEX_NEXT_DAY_MID_MORNING';
    const FIRST_OVERNIGHT = 'FIRST_OVERNIGHT';
    const GROUND_HOME_DELIVERY = 'GROUND_HOME_DELIVERY';
    const INTERNATIONAL_ECONOMY = 'INTERNATIONAL_ECONOMY';
    const INTERNATIONAL_ECONOMY_FREIGHT = 'INTERNATIONAL_ECONOMY_FREIGHT';
    const INTERNATIONAL_FIRST = 'INTERNATIONAL_FIRST';
    const INTERNATIONAL_PRIORITY_FREIGHT = 'INTERNATIONAL_PRIORITY_FREIGHT';
    const PRIORITY_OVERNIGHT = 'PRIORITY_OVERNIGHT';
    const PRIORITY_OVERNIGHT_EXTRA_HOURS = 'PRIORITY_OVERNIGHT_EXTRA_HOURS';
    const SAME_DAY = 'SAME_DAY';
    const SAME_DAY_CITY = 'SAME_DAY_CITY';
    const SMART_POST = 'SMART_POST';
    const STANDARD_OVERNIGHT = 'STANDARD_OVERNIGHT';
    const FEDEX_STANDARD_OVERNIGHT_EXTRA_HOURS = 'FEDEX_STANDARD_OVERNIGHT_EXTRA_HOURS';
}
